prepare:
	javac Account.java
	javac Transaction.java
	javac FileParser.java
	javac Backend.java
	javac TransactionType.java

run:
	java Backend master.txt trans1.txt trans2.txt

clean:
	rm *.class
	rm concat.txt