prepare:
	javac Account.java
	javac Transaction.java
	javac TransactionType.java
	javac FileParser.java
	javac FileUpdater.java
	javac Backend.java

run:
	java Backend master.txt trans1.txt trans2.txt

clean:
	rm *.class
	rm concat.txt
