prepare:
	javac backend/Account.java
	javac backend/Transaction.java
	javac backend/TransactionType.java
	javac backend/FileParser.java
	javac backend/FileUpdater.java
	javac backend/Backend.java

run:
	java backend.Backend master.txt trans1.txt trans2.txt

clean:
	rm backend/*.class
	rm concat.txt
	rm newMaster.txt