prepare:
	javac banksys/Account.java
	javac banksys/Transaction.java
	javac banksys/TransactionType.java
	javac banksys/FileParser.java
	javac banksys/FileUpdater.java
	javac banksys/Backend.java

run:
	java banksys.Backend master.txt trans1.txt trans2.txt

clean:
	rm banksys/*.class
	rm concat.txt
	rm newMaster.txt